name: The Terminal
favicon: null
layout_spectrum: 0.55873
typography_spectrum: 0.54964
title: The Terminal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#272727'
    - '#8a8a8a'
    - '#555555'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.7307188459672034
  rhythmicContrast: 0.7723409098107368
purpose: []
